### ISSUE TITLE
 update both Agent and Store links on line 77 in upload.md

### ISSUE THREAD

**Issue by gobengo** [web3-storage/www#42]
Motivation:
* moved here from https://github.com/web3-storage/www/pull/34/
```[tasklist]
### Tasks
- [ ] https://github.com/web3-storage/w3up/pull/1141
- [x] update links from website to the api docs
- [ ] https://github.com/web3-storage/www/pull/48
- [x] test on staging
- [x] test on prod
```

**Comment by gobengo** [comment]
needs review of https://github.com/web3-storage/www/pull/48

**Comment by gobengo** [comment]
fixed at https://web3.storage/docs/how-to/upload/
